name: qwi365
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  xml: ^6.6.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  google_maps_flutter: ^2.14.2
  custom_info_window: ^1.0.1
  intl: ^0.20.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

